spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER:postgres}
    password: ${LOCAL_DB_PASSWORD:postgres}
    hikari:
      pool-name: Hikari-PostgreSQL
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 1000
      max-lifetime: 200000
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        jdbc.lob.non_contextual_creation: true
        generate_statistics: true
        format_sql: true
    show-sql: true
