name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository ì ‘ê·¼
        uses: actions/checkout@v4

      - name: JDK 21 ì…‹íŒ…
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: í”„ë¡œì íŠ¸ ë¹Œë“œ
        env:
          SECRET_MANAGER_TOKEN: ${{ secrets.SECRET_MANAGER_TOKEN }}
          SECRET_MANAGER_WORKSPACE: ${{ secrets.SECRET_MANAGER_WORKSPACE }}
        run: |
          ./gradlew build

      - name: Set build status output
        id: set_status
        run: echo "::set-output name=build_status::${{ job.status }}"

      - name: Comment on Pull Request
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const { GITHUB_TOKEN } = process.env;
            const github = require('@actions/github');

            const status = '${{ steps.set_status.outputs.build_status }}';
            const message = status === 'success' ? 'âœ…ë¹Œë“œ ì„±ê³µ\nğŸš€ì¶œê²© ì¤€ë¹„ ì™„ë£Œ ğŸš€' : 'âŒë¹Œë“œ ì‹¤íŒ¨\nğŸ˜µì½”ë“œ í™•ì¸ì´ í•„ìš”í•´ìš”ğŸ˜µ';

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `${message}`
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
