name: CI

on:
  issue_comment:
    types: [ created ]

jobs:
  build:
    name: ready for launch (CI)
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'ì¶œê²©ì¤€ë¹„')}}
    steps:
      - name: Repository ì ‘ê·¼
        uses: actions/checkout@v4

      - name: JDK 21 ì…‹íŒ…
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle ì˜ì¡´ì„± ìºì‹±
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: í”„ë¡œì íŠ¸ ë¹Œë“œ
        env:
          SECRET_MANAGER_TOKEN: ${{ secrets.SECRET_MANAGER_TOKEN }}
          SECRET_MANAGER_WORKSPACE: ${{ secrets.SECRET_MANAGER_WORKSPACE }}
        run: |
          ./gradlew build

      - name: Set build status output
        id: set_status
        run: echo "build_status=${{ job.status }}" >> $GITHUB_OUTPUT

      - name: Comment on Pull Request
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ steps.set_status.outputs.build_status }}';
            const message = status === 'success' ? 'âœ… ë¹Œë“œ ì„±ê³µ âœ…\nğŸš€ ì¶œê²© ì¤€ë¹„ ì™„ë£Œ ğŸ‘¨ğŸ»â€ğŸš€' : 'âŒâŒ ë¹Œë“œ ì‹¤íŒ¨ âŒâŒ\nğŸ˜µğŸ˜µâ€ğŸ’« ì½”ë“œ í™•ì¸ì´ í•„ìš”í•´ìš” ğŸ˜µğŸ˜µâ€ğŸ’«';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `${message}`
            });
